# Default values for redis-sentinel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3

image:
  repository: 
  tag: v1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# When redis failover occured, cliient-reconfig-script will change specified ExternalIP to new master IP.
service:
  ExternalName:
    monitorName:
    monitorIP:
  type: ClusterIP
  port: 26379

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

sentinelConfig: |
  bind 0.0.0.0
  port 26379
  sentinel monitor redis varusan-kvs-01 6379 1
  sentinel parallel-syncs redis 1
  sentinel down-after-milliseconds redis 10000
  sentinel failover-timeout redis 20000
  # sentinel notification-script redis /etc/redis/notify.sh
  sentinel client-reconfig-script redis /etc/redis/reconfig.sh
