apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  labels:
    app: {{ template "redis-sentinel.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  sentinel.conf: {{ toYaml .Values.sentinelConfig | indent 2 }}
  {{ $root := . }} {{ range $path, $bytes := .Files.Glob "**.sh" }}
  {{ base $path }}: {{ $root.Files.Get $path | toYaml |indent 2 }}
  {{ end }}
