apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-sentinel.fullname" . }}
  labels:
    app: {{ include "redis-sentinel.name" . }}
    chart: {{ include "redis-sentinel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 26379
      protocol: TCP
      name: sentinel
  selector:
    app: {{ include "redis-sentinel.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ExternalName.monitorName }}
  labels:
    app: {{ include "redis-sentinel.name" . }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.ExternalName.monitorIP }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ExternalName.kvs01 }}
  labels:
    app: {{ include "redis-sentinel.name" . }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.ExternalName.kvs01_IP }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ExternalName.kvs02 }}
  labels:
    app: {{ include "redis-sentinel.name" . }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.ExternalName.kvs02_IP }}
